name: Build & Benchmark x86_64

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: build-and-benchmark-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd x86_64
          make all

      - name: Run benchmarks
        run: |
          ./x86_64/benchmark.sh
          sed -i '1iNotice: Benchmarks are generated on GitHub Actions using GitHub Actions runners (x86_64 Linux)' ./x86_64/benchmark.txt
          sed -i '1iNotice: Benchmarks are generated on GitHub Actions using GitHub Actions runners (x86_64 Linux)' ./x86_64/benchmark_verbose.txt

      - name: Upload benchmark logs
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks
          path: |
            x86_64/benchmark.txt
            x86_64/benchmark_verbose.txt
