name: Build & Benchmark x86_64

on:
  push:
    branches: [main]

permissions:
  contents: write 

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd x86_64
          make all

      - name: Run benchmarks
        run: |
          ./x86_64/benchmark.sh
          sed -i '1iNotice: Benchmarks are generated on GitHub Actions using GitHub Actions runners (x86_64 Linux)' ./x86_64/benchmark.txt
          sed -i '1iNotice: Benchmarks are generated on GitHub Actions using GitHub Actions runners (x86_64 Linux)' ./x86_64/benchmark_verbose.txt

      - name: Commit benchmark log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./x86_64/benchmark.txt ./x86_64/benchmark_verbose.txt
          git commit -m "Update benchmark log" || echo "No changes to commit"
          git push origin HEAD:benchmarks
